{% set name = "apache-sedona" %}
{% set version = "1.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 723f8fe47b9dc2e857524ccf6d192dac1316bf80a8a3f1ea9f55427fb5ebba6f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
  run:
    - attrs
    - pyspark
    - python
    - shapely >=1.7.0
    - rasterio >=1.2.10

test:
  imports:
    - sedona
    - sedona.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://sedona.apache.org
  summary: Apache Sedona is a cluster computing system for processing large-scale spatial data
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dsangillo
    - mxr-conda
    - jiayuasu
