{% set name = "apache-sedona" %}
{% set version = "1.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-sedona-{{ version }}.tar.gz
  sha256: b692581ad3946ac84ccb3f9f6280b00c9f7c8104919b818d77e7886a1f4d294d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - attrs
    - pyspark
    - python >=3.6
    - shapely

test:
  imports:
    - sedona
    - sedona.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://sedona.apache.org
  summary: Apache Sedona is a cluster computing system for processing large-scale spatial data
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dsangillo
    - mxr-conda
