{% set name = "apache-sedona" %}
{% set version = "1.5.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 36fd640ea93a860b15bb2d6a75035ddbd5bf899fb17af996b1b29c0a55c4612f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
  run:
    - attrs
    - pyspark
    - python
    - shapely >=1.7.0, <2.0

test:
  imports:
    - sedona
    - sedona.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://sedona.apache.org
  summary: Apache Sedona is a cluster computing system for processing large-scale spatial data
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dsangillo
    - mxr-conda
    - jiayuasu
